config/routes.rb
KeshariyaCompany::Application.routes.draw do
  scope '/admin' do
    resources :careers
    resources :projects
	  resources :project_types
	  resources :pages
	  resources :testimonials
	  resources :contacts
  end

  devise_for :admin_users
  resource :admin_users, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end
  

  root 'home#index'
  get 'about-us'       => 'home#about_us',       :as => :about_us
  match "contact-us"   => "home#contact_us",     :as => :contact_us,  via: [:get, :post]
  get 'services'       => 'home#services',       :as => :services
  get 'blogs'          => 'home#blogs',          :as => :blogs
  get 'careers'        => 'home#careers',        :as => :careers_main
  get 'portfolio-list' => 'home#portfolio_list', :as => :portfolio_list
  get '/portfolio/:id' => 'home#portfolio',      :as => :portfolio
  get '/admin'         => 'testimonials#index',  :as => :admin

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout false, only: [:portfolio]

  #before_action :fetch_services, only: [:home, :services]
  
  def index
    @introduction                = Page.find_by(name: "Home Page Introduction")
    @staticts_countries_covered  = Page.find_by(name: "Staticts Countries Covered")
    @staticts_satisfied_clients  = Page.find_by(name: "Staticts Satisfied Clients")
    @staticts_finished_projects  = Page.find_by(name: "Staticts Finished Projects")
    @staticts_resources_strength = Page.find_by(name: "Staticts Resources Strength")
  end

  def about_us
    @introduction                = Page.find_by(name: "About Us Page Introduction")
    @staticts_countries_covered  = Page.find_by(name: "Staticts Countries Covered")
    @staticts_satisfied_clients  = Page.find_by(name: "Staticts Satisfied Clients")
    @staticts_finished_projects  = Page.find_by(name: "Staticts Finished Projects")
    @staticts_resources_strength = Page.find_by(name: "Staticts Resources Strength")
  end

  def contact_us
    #@page = Page.find_by(name: "Contact")
    if request.get?
      @contact = Contact.new
    else
      @contact = Contact.new(contact_params)
      if @contact.save
        #ContactMailer.contact_get_detail(@contact).deliver
        flash[:success] = "Message Sent. Thank You for Contacting Me"
        redirect_to root_path
      else
        render :action => "contact_us"
      end
    end
  end

  def careers
    @careers = Career.all
  end
  
  def services
  end

  def portfolio_list
  	@projects = Project.all.includes(:project_type)
    @project_types = ProjectType.all
  end

  def portfolio
    @project = Project.find(params[:id])
  end

  def blogs
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :message, :email)
  end

  def fetch_services
    # @service_mobile_development = Page.find_by(name: "Service Mobile Development")
    # @service_website_development = Page.find_by(name: "Service Website Development")
    # @servive_seo_desining = Page.find_by(name: "Service SEO & Designing")
  end
end

app/views/home/blogs.html.erb
<!-- 	<section class="pageheader-default text-center">
	<div class="semitransparentbg">
		<h1 class="animated fadeInLeftBig notransition">Blog Home</h1>
		<p class="animated fadeInRightBig  notransition container wowbreadcr">
			 Home / Blog / Homepage
		</p>
	</div>
	</section>
	<div class="wrapsemibox">
		<div class="semiboxshadow text-center">
			<img src="/assets/shp.png" class="img-responsive" alt="">
		</div>
		<section class="container animated fadeInDown notransition">
		<div class="row blogindex">
		
			<div class="col-md-9">
				<div class="text-center">
					<h2>Merry Christmas</h2>
					<span class="meta bottomspace30">By <a href="http://www.wowthemes.net/demo/calypso/blogindex.html#" title="Posts by Roy Sanders" rel="author">Roy Sanders</a><span class="bullet">•</span> November 5, 2013 <span class="bullet">•</span><a href="http://www.wowthemes.net/demo/calypso/blogindex.html#" title="View all posts in Food &amp; Health" rel="category tag">Food &amp; Health</a></span>
				</div>
				<div class="row">
					<div class="col-md-12">
						<p class="lead">
							<img src="/assets/desktop3.png" class="pull-left img-responsive" alt="" style="max-width:180px;">
							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque rutrum pellentesque imperdiet. Nulla lacinia iaculis nulla non pulvinar. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut eu risus enim, ut pulvinar lectus.
						</p>
						<a href="http://www.wowthemes.net/demo/calypso/blogindex.html#" class="btn btn-default">Read more</a>
						<hr class="clearfix">
						<div class="text-center">
							<h2>Finding Treasures</h2>
							<span class="meta bottomspace30">By <a href="http://www.wowthemes.net/demo/calypso/blogindex.html#" title="Posts by Roy Sanders" rel="author">Roy Sanders</a> <span class="bullet">•</span> November 5, 2013 <span class="bullet">•</span> <a href="http://www.wowthemes.net/demo/calypso/blogindex.html#" title="View all posts in Food &amp; Health" rel="category tag">Food &amp; Health</a></span>
						</div>
						<p class="lead">
							<img src="/assets/desktop2.png" class="pull-left img-responsive" alt="" style="max-width:180px;">
							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque rutrum pellentesque imperdiet. Nulla lacinia iaculis nulla non pulvinar. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut eu risus enim, ut pulvinar lectus.
						</p>
						<a href="http://www.wowthemes.net/demo/calypso/blogindex.html#" class="btn btn-default">Read more</a>
						<hr class="clearfix">
						<div class="text-center">
							<h2>Once Upon a Time</h2>
							<span class="meta bottomspace30">By <a href="http://www.wowthemes.net/demo/calypso/blogindex.html#" title="Posts by Roy Sanders" rel="author">Roy Sanders</a><span class="bullet">•</span> November 5, 2013 <span class="bullet">•</span><a href="http://www.wowthemes.net/demo/calypso/blogindex.html#" title="View all posts in Food &amp; Health" rel="category tag">Food &amp; Health</a></span>
						</div>
						<p class="lead">
							<img src="/assets/slide1-1.png" class="pull-left img-responsive" alt="" style="max-width:180px;">
							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque rutrum pellentesque imperdiet. Nulla lacinia iaculis nulla non pulvinar. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut eu risus enim, ut pulvinar lectus.
						</p>
						<a href="http://www.wowthemes.net/demo/calypso/blogindex.html#" class="btn btn-default">Read more</a>
						<hr class="clearfix">
						<ul class="pagination pagination-lg">
							<li class="disabled"><a href="http://www.wowthemes.net/demo/calypso/blogindex.html#">«</a></li>
							<li class="active"><a href="http://www.wowthemes.net/demo/calypso/blogindex.html#">1 <span class="sr-only">(current)</span></a></li>
							<li><a href="http://www.wowthemes.net/demo/calypso/blogindex.html#">2</a></li>
							<li><a href="http://www.wowthemes.net/demo/calypso/blogindex.html#">3</a></li>
							<li><a href="http://www.wowthemes.net/demo/calypso/blogindex.html#">4</a></li>
							<li><a href="http://www.wowthemes.net/demo/calypso/blogindex.html#">5</a></li>
							<li><a href="http://www.wowthemes.net/demo/calypso/blogindex.html#">»</a></li>
						</ul>
					</div>
				</div>
			</div>

			<div class="col-md-3">
				<aside class="sidebar topspace30">
				<div class="wowwidget">
					<h4>Categories</h4>
					<ul class="categories">
						<li><a href="http://www.wowthemes.net/demo/calypso/blogindex.html#">Music &amp; Films</a></li>
						<li><a href="http://www.wowthemes.net/demo/calypso/blogindex.html#">Home Decoration</a></li>
						<li><a href="http://www.wowthemes.net/demo/calypso/blogindex.html#">Food &amp; Health</a></li>
						<li><a href="http://www.wowthemes.net/demo/calypso/blogindex.html#">Lifestyle Green</a></li>
						<li><a href="http://www.wowthemes.net/demo/calypso/blogindex.html#">Future Technology</a></li>
					</ul>
				</div>
				<div class="wowwidget">
					<div class="tabs">
						<ul class="nav nav-tabs">
							<li class="active"><a href="http://www.wowthemes.net/demo/calypso/blogindex.html#popularPosts" data-toggle="tab"><i class="icon icon-star"></i> Popular</a></li>
							<li><a href="http://www.wowthemes.net/demo/calypso/blogindex.html#recentPosts" data-toggle="tab">Recent</a></li>
						</ul>
						<div class="tab-content">
							<div class="tab-pane active" id="popularPosts">
								<ul class="unstyled">
									<li>
									<div class="tabbedwidget">
										<a href="http://www.wowthemes.net/demo/calypso/blog-single.html">
										<img src="/assets/showcase1.jpg" alt="">
										</a>
									</div>
									<div class="post-info">
										<a href="http://www.wowthemes.net/demo/calypso/blog-single.html">Finding Treasures</a>
										<div class="post-meta">
											 Dec 12, 2013
										</div>										
									</div>
									</li>
									<li>
									<div class="tabbedwidget">
										<a href="http://www.wowthemes.net/demo/calypso/blog-single.html">
										<img src="/assets/showcase2.jpg" alt="">
										</a>
									</div>
									<div class="post-info">
										<a href="http://www.wowthemes.net/demo/calypso/blog-single.html">Once Upon a Time</a>
										<div class="post-meta">
											 Jan 16, 2014
										</div>
									</div>
									</li>
									<li>
									<div class="tabbedwidget">
										<a href="http://www.wowthemes.net/demo/calypso/blog-single.html">
										<img src="/assets/showcase3.jpg" alt="">
										</a>
									</div>
									<div class="post-info">
										<a href="http://www.wowthemes.net/demo/calypso/blog-single.html">Midnight in Paris</a>
										<div class="post-meta">
											 Sep 28, 2014
										</div>
									</div>
									</li>
								</ul>
							</div>
							<div class="tab-pane" id="recentPosts">
								<ul class="unstyled">
									<li>
									<div class="tabbedwidget">
										<a href="http://www.wowthemes.net/demo/calypso/blog-single.html">
										<img src="/assets/showcase4.jpg" alt="">
										</a>
									</div>
									<div class="post-info">
										<a href="http://www.wowthemes.net/demo/calypso/blog-single.html">From Rome with Love</a>
										<div class="post-meta">
											 Jan 10, 2014
										</div>
									</div>
									</li>
									<li>
									<div class="tabbedwidget">
										<a href="http://www.wowthemes.net/demo/calypso/blog-single.html">
										<img src="/assets/showcase3.jpg" alt="">
										</a>
									</div>
									<div class="post-info">
										<a href="http://www.wowthemes.net/demo/calypso/blog-single.html">Midnight in Paris</a>
										<div class="post-meta">
											 Feb 13, 2014
										</div>
									</div>
									</li>
									<li>
									<div class="tabbedwidget">
										<a href="http://www.wowthemes.net/demo/calypso/blog-single.html">
										<img src="/assets/showcase2.jpg" alt="">
										</a>
									</div>
									<div class="post-info">
										<a href="http://www.wowthemes.net/demo/calypso/blog-single.html">City Lights</a>
										<div class="post-meta">
											 Aug 25, 2014
										</div>
									</div>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
				<div class="widget">
					<h4>About Us</h4>
					<p>
						Nulla nunc dui, tristique in semper vel, congue sed ligula. Nam dolor ligula, faucibus id sodales in, auctor fringilla libero. Nulla nunc dui, tristique in semper vel. Nam dolor ligula, faucibus id sodales in, auctor fringilla libero.
					</p>
				</div>
				</aside>
			</div>
		</div>
		</section>


	</div> -->

app/views/home/careers.html.erb
<% provide(:title, 'Careers') %>
<script type="text/javascript" src="/assets/jquery.min.js"></script>
  <!-- start header tag-->
  <!--start page banner-->
  <div class="pagebanner career-banner">
                    <span id="bgback" role="img">
                        <span class="inner">
                        </span>
                    </span>
                </div>
  <!-- end page banner -->
  <!-- start page heading -->
  <div id="action_box" data-arrowpos="center">
    <div class="container">
      <div class="row">
        <div class="span12">
          <h4 class="text">
            <div align="center">Career: Apsolute Technologies</div>
          </h4>
        </div>
      </div>
    </div>
  </div>
  <!-- end page heading -->
  <!-- start inner content section-->
  <section id="content">
    <!--start 1st container-->
    <div class="container">
      <div class="row">
        <p class="custom_text">
          We are the perfect destination for every sedulous individual to give you career successful growth and evolution.
          Our working ecosystem is the appropriate for every new member as there is always willingness from seniors and other employees to help you.
          You can be sure at apsolute technologies that you always have your team to back you up.
        </p>
        <p class="custom_text">
          We are always looking for talented and enthusiastic new employees who can  give contributions to the success of our company. Take a view to our career pages. We want you to realize your prospective. You want to be canonicalized for your work. We want you to consummate your ambitions.
        </p>
      </div>
      <% if @careers.present? %>
        <div class="row ">
          <h3 class="m_title">Current Openings</h3>
          <div id="content-expand">
            <div class="collapsing">
              <% @careers.each do |career| %>
                <h4 class="expand"><span class="colps-heading"><%= career.title %></span></h4>
                <div class="collapse">
                  <table>
                    <tbody>
                      <tr>                          
                        <td>Experience :</td>
                        <td><%= career.experience %></td>
                      </tr>
                      <tr>
                        <td>Involvement : &nbsp;</td>
                        <td><%= career.involvement %></td>
                      </tr>
                      <% if career.location.present? %>
                        <tr>
                          <td>Location: </td>
                          <td><%= career.location %></td>
                        </tr>
                      <% end %>
                      <% if career.package.present? %>
                        <tr>
                          <td>Package :</td>
                          <td><%= career.package %></td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
      <div class="row ">
        <div class="span12">
          <div class="keywordbox">Send your resume on apsolutetechnology@gmail.com</div>
        </div>
      </div>
    </div>
    <!--end 1st container-->
  </section>
  <!-- end inner content section-->
<script type="text/javascript" src="/assets/bootstrap.js"></script>
<script type="text/javascript" src="/assets/expand.js"></script>
<script type="text/javascript" src="/assets/znscript.js"></script>
<script type="text/javascript">
  //for expand collapse
  $(document).ready(function() {
    $("#content-expand h4.expand").toggler();
    
  });
  
</script>

app/views/home/portfolio.html.erb
<% provide(:title, 'Portfolio') %>
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title><%= @project.project_title %></title>
   </head>
   <body>
      
      <div style="display: block;" data-action="" class="cbp-popup-wrap cbp-popup-singlePage cbp-popup-singlePage-open cbp-popup-singlePage-sticky">
         <div class="cbp-popup-content">
            <div class="cbp-l-project-title"><%= @project.project_title %></div>
            <div class="cbp-slider">
               <ul class="cbp-slider-wrap">
                  <li class="cbp-slider-item">
                  	<%= image_tag @project.avatar(:pfolio, false), :class => "cbp-l-project-img" %>
                  </li>
               </ul>
            </div>
            <div class="cbp-l-project-container">
               <div class="cbp-l-project-desc">
                  <div class="cbp-l-project-desc-title"><span>Project Description</span></div>
                  <div class="cbp-l-project-desc-text">
                     <%= @project.short_description %>
                  </div>
               </div>
               <div class="cbp-l-project-details">
                  <div class="cbp-l-project-details-title"><span>Project Details</span></div>
                  <ul class="cbp-l-project-details-list">
                     <li><strong>Categories</strong><%= @project.project_type.name %></li>
                  </ul>
               </div>
            </div>
            <br>
            <br>
            <br>
         </div>
         <div class="cbp-popup-loadingBox"></div>
         
         <div class="cbp-popup-navigation-wrap">
            <div class="cbp-popup-navigation">
               <button data-action="close" type="button" title="Close (Esc arrow key)" class="cbp-popup-close"></button>
            </div>
         </div>
      </div>
   </body>
</html>

app/views/home/portfolio_list.html.erb
<% provide(:title, 'Portfolio List') %>
<script type="text/javascript" src="assets/cubeportfolio-plugin.js"></script>
<!--start page banner-->
<div id="page_header" class="uh_about-us">
  <!--start page banner background image-->
  <div class="bgback"><img src="/assets/portfolio.png" alt="Portfolio"></div>
  <!--end page banner background image-->
  <div class="container">
    <div class="row">
      <div class="span6"></div>
      <div class="span6">
        <div class="header-titles"></div>
      </div>
    </div>
    <!-- end row -->
  </div>
</div>
<!-- end page banner -->
<!-- start page heading -->
<div id="action_box" data-arrowpos="center">
  <div class="container">
    <div class="row">
      <div class="span12">
        <h4 class="text">
          <div align="center">Portfolio: Apsolute Technologies</div>
        </h4>
      </div>
    </div>
  </div>
</div>
<!-- end page heading -->
<!-- start inner content section-->
<section id="content">
  <!--start 1st container-->
  <div class="container">
    <div class="row ">
      <div id="filters-container" class="cbp-l-filters-button">      
        <div data-filter="*" class="cbp-filter-item-active cbp-filter-item">
          All
          <div class="cbp-filter-counter"></div>
        </div>
        <% @project_types.each do |project_type| %>
          <div data-filter=".<%= project_type.name.gsub(' ','_') %>" class="cbp-filter-item">
            <%= project_type.name %>
            <div class="cbp-filter-counter"></div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div id="grid-container" class="cbp-l-grid-projects">
        <ul class="cbp-wrapper">
          <% @projects.each do |project| %>
            <li class="cbp-item <%= project.project_type.name.gsub(' ','_') %>">
              <div class="cbp-item-wrapper">
                <div class="cbp-caption">
                  <div class="cbp-caption-defaultWrap">
                    <%= image_tag(project.avatar(:pfolio, false))%>
                    <!-- <img src="/assets/portfolio/small/1.jpg" alt="" width="100%"> -->
                  </div>
                  <div class="cbp-caption-activeWrap">
                    <div class="cbp-l-caption-alignCenter">
                      <div class="cbp-l-caption-body">
                        <a href="<%= portfolio_path(project) %>" class="cbp-singlePage cbp-l-caption-buttonLeft"><img src="/assets/link.png"></a>
                        <a href="<%= project.avatar(:pfolio, false) %>" class="cbp-lightbox cbp-l-caption-buttonRight" data-title="<%= project.project_title %>"><img src="/assets/lupe.png"></a>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="cbp-l-grid-projects-title"><a href="<%= portfolio_path(project) %>" class="cbp-singlePage"><%= project.project_title %></a></div>
                <div class="cbp-l-grid-projects-desc"><%= project.short_description.truncate(50) %></div>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <!--end 1st container-->
</section>
<!-- end inner content section-->
<!-- load main js -->
<script type="text/javascript" src="/assets/portfoliomain.js"></script>
<!-- <section class="pageheader-default text-center">
  <div class="semitransparentbg">
    <h1 class="animated fadeInLeftBig notransition">Portfolio</h1>
    <p class="animated fadeInUp container page-description"></p>
  </div>
  </section>
  
  <div class="wrapsemibox">
  <div class="semiboxshadow text-center">
  </div>
  
  <section class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <div id="filter" class="animated fadeInRight">
          <ul>
            <li><a href="" data-filter="*" class="selected"><i class="icon icon-reorder"></i> All Items</a></li>
            <%# @project_types.each do |project_type| %>
              <li><a href="" data-filter=".<%#= project_type.name.gsub(' ','_') %>"><i class="icon icon-th-large"></i> <%#= project_type.name %></a></li>
            <%# end %>
          </ul>
        </div>
      </div>
    </div>
    
    <div id="content" style="position: relative; overflow: hidden; height: 3242px;" class="isotope">
      
      <%# @projects.each do |project| %>
        <div class="boxportfolio3 item <%#= project.project_type.name.gsub(' ','_') %> isotope-item" style="position: absolute; left: 0px; top: 0px; -webkit-transform: translate(0px, 1289px);">
          <div class="boxcontainer">
            <%#= image_tag(project.avatar(:pfolio, false))%>
            <div class="roll" style="opacity: 0;">
              <div class="wrapcaption">
                <a href="<%#= portfolio_path(project) %>"><i class="icon-link captionicons"></i></a>
                <a data-gal="prettyPhoto[gallery1]" href="<%#= project.avatar %>" title="Title Here"><i class="icon-zoom-in captionicons"></i></a>
              </div>
            </div>
            <h1><%#= link_to project.project_title, portfolio_url(project) %></h1>
            <p><%#= project.short_description.truncate(50) %></p>
          </div>
        </div>
      <%# end %>
    </div>
  </section>
  </div> -->

app/views/home/services.html.erb
<% provide(:title, 'Services') %>
<div class="pagebanner services-banner">
                    <span id="bgback" role="img">
                        <span class="inner">
                        </span>
                    </span>
                </div>
<!-- end page_header -->
<div id="action_box" data-arrowpos="center">
   <div class="container">
      <div class="row">
         <div class="span12">
            <h4 class="text">
               <div align="center">
                  Services
               </div>
            </h4>
         </div>
      </div>
   </div>
</div>
<!-- end action box -->
<section id="content">
   <div class="container">
      <div class="row ">
         <div class="span4">
            <p class="custom_text">
               We provide high quality services for development of the website, mobile application and also maintanance.
               <br/>
               <br/>
               We provide every solution related to mobile and web applications.
               <br/>
               <br/>
               Our team gives the capability to design, Conceptualize, develop and deliver complex and useful applications.
               <br/>
               <br/>
               Our approach for development depends upon client's requirment. As a result, we are able to deliver satisfied result.
            </p>
         </div>
         <div class="span8">
           <p></p>
             <div id="skills_diagram">
               <div class="legend">
                      <h4>Legend:</h4>
                      <ul class="skills">
                         <li data-percent="45" style="background-color:#56BC9A;">Mobile</li>
                         <li data-percent="60" style="background-color:#FF9900;">Web Development</li>
                         <li data-percent="50" style="background-color:#89877B;">SEO &amp; Design</li>
                         <li data-percent="70" style="background-color:#66CCFF;">E-Commerce</li>
                         <li data-percent="80" style="background-color:#28465e;">CMS Devlopment</li>
                      </ul>
                  <!-- end the skills -->
               </div>
               <div id="thediagram" data-width="600" data-height="600" data-maincolor="#193340" data-maintext="Services" data-fontsize="15px Arial" data-textcolor="#ffffff">
               </div>
               <script type="text/javascript" src="/assets/init.js"></script>
            </div>
            <!-- end skills diagram -->
            <p>
            </p>
         </div>
      </div>
      <div class="row ">
         <div class="span12">
            <div class="row noMargin">
               <div class="span12">
                  <h4 class="smallm_title centered bigger">
                     <span>
                     Services We Provide
                     </span>
                  </h4>
               </div>
               <div class="span3">
                  <p class="custom_text">
                     <em>
                     We provide top notch services to meet client's requirement with deadlines. All major technology services are provided by us including Mobile, Web, CMS , Development, and Maintenance.
                     </em>
                  </p>
               </div>
               <div class="span3 feature_box style2">
                  <div class="box">
                     <span class="icon">
                     <img src="assets/ico-plan.png" alt="">
                     </span>
                     <h4 class="title padding-text">
                        Mobile
                     </h4>
                  </div>
               </div>
               <div class="span3 feature_box style2">
                  <div class="box">
                     <span class="icon">
                     <img src="assets/ico-plan.png" alt="">
                     </span>
                     <h4 class="title padding-text">
                        Web Development
                     </h4>
                  </div>
               </div>
               <div class="span3 feature_box style2">
                  <div class="box">
                     <span class="icon">
                     <img src="assets/ico-plan.png" alt="">
                     </span>
                     <h4 class="title padding-text">
                        SEO &amp; Design
                     </h4>
                  </div>
               </div>
               <div class="span3 feature_box style2">
                  <div class="box">
                     <span class="icon">
                     <img src="assets/ico-plan.png" alt="">
                     </span>
                     <h4 class="title padding-text">
                        E-commerce
                     </h4>
                  </div>
               </div>
               <div class="span3 feature_box style2">
                  <div class="box">
                     <span class="icon">
                     <img src="assets/ico-plan.png" alt="">
                     </span>
                     <h4 class="title padding-text">
                        CMS Development
                     </h4>
                  </div>
               </div>
               
            </div>
         </div>
      </div>
      <div class="row ">
         <div class="span10">
            <h3 class="m_title" style="margin-top:25px;">
               If You are not failing every now and again , it's a sign you are not doing anything very innovative. If my films don't show a profit I know I am doing something right.
            </h3>
            <p>
               Call us today at (+91)79 40326868 or Email us at apsolutetechnology@gmail.com
            </p>
         </div>
         <div class="span2">
            <a href="<%= contact_us_path %>" class="circlehover with-symbol" data-size="" data-position="top-left" data-align="right" target="_self">
            <span class="text">
            Contact Us
            </span>
            <span class="symbol">
            <img src="assets/ok.png" alt="">
            </span>
            </a>
         </div>
      </div>
      <div class="row ">
         <div class="span12">
            <div class="process_steps fixclear">
               <div class="step intro">
                  <h3>
                     Our Working Process
                     <strong>
                     In 3 Steps
                     </strong>
                  </h3>
                  <p>
                     Our simple working process divided into main three steps.
                  </p>
               </div>
               <!-- end step -->
               <div class="step step1">
                  <div class="icon" data-animation="pulse">
                     <img src="assets/ico-plan.png" alt="">
                  </div>
                  <h3>
                     Conceptualization
                  </h3>
                  <p>
                     We understand the requirement and plan to achive the same at best level.
                  </p>
               </div>
               <div class="step step2">
                  <div class="icon" data-animation="tada">
                     <img src="assets/ico-designdev.png" alt="">
                  </div>
                  <h3>
                     Design &amp; Develop
                  </h3>
                  <p>
                     Our development process is always focused on client requirements.
                  </p>
               </div>
               <div class="step step3">
                  <div class="icon" data-animation="fadeOutRightBig">
                     <img src="assets/ico-launch.png" alt="">
                  </div>
                  <h3>
                     Test &amp; Maintenance
                  </h3>
                  <p>
                     Out testers always focus on delivering high quality product.
                  </p>
               </div>
            </div>
         </div>
      </div>
   </div>
</section>
<!-- end #content -->