config/routes.rb
KeshariyaCompany::Application.routes.draw do
  scope '/admin' do
    resources :careers
    resources :projects
	  resources :project_types
	  resources :pages
	  resources :testimonials
	  resources :contacts
  end

  devise_for :admin_users
  resource :admin_users, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end
  

  root 'home#index'
  get 'about-us'       => 'home#about_us',       :as => :about_us
  match "contact-us"   => "home#contact_us",     :as => :contact_us,  via: [:get, :post]
  get 'services'       => 'home#services',       :as => :services
  get 'blogs'          => 'home#blogs',          :as => :blogs
  get 'careers'        => 'home#careers',        :as => :careers_main
  get 'portfolio-list' => 'home#portfolio_list', :as => :portfolio_list
  get '/portfolio/:id' => 'home#portfolio',      :as => :portfolio
  get '/admin'         => 'testimonials#index',  :as => :admin

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :email,:password,:password_confirmation
end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController
  layout 'admin'
	before_filter :authenticate_admin_user!

  def edit
    @admin_user = current_admin_user
  end

  def update_password
    @admin_user = current_admin_user
    if @admin_user.update_with_password(admin_user_params)
      sign_in @admin_user, :bypass => true
      flash[:success] = "Password Changed Successfully"
      redirect_to admin_path
    else
      logger.warn(@admin_user.errors.full_messages)
      render "edit"
    end
  end

  private

  def admin_user_params    
    params.required(:admin_user).permit(:password, :password_confirmation,:current_password)
  end
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/views/admin_users/edit.html.erb
<% provide(:title, 'Admin') %>
<%- model_class = Testimonial -%>
<div class="page-header">
  <h1>Change Password</h1>
</div>
<%= simple_form_for @admin_user, url: update_password_admin_users_path, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.input :current_password %>
  <div class="form-actions">
    <%= f.button :submit, 'Change Password', :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admin_path, :class => 'btn' %>
  </div>
<% end %>