config/routes.rb
KeshariyaCompany::Application.routes.draw do
  scope '/admin' do
    resources :careers
    resources :projects
	  resources :project_types
	  resources :pages
	  resources :testimonials
	  resources :contacts
  end

  devise_for :admin_users
  resource :admin_users, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end
  

  root 'home#index'
  get 'about-us'       => 'home#about_us',       :as => :about_us
  match "contact-us"   => "home#contact_us",     :as => :contact_us,  via: [:get, :post]
  get 'services'       => 'home#services',       :as => :services
  get 'blogs'          => 'home#blogs',          :as => :blogs
  get 'careers'        => 'home#careers',        :as => :careers_main
  get 'portfolio-list' => 'home#portfolio_list', :as => :portfolio_list
  get '/portfolio/:id' => 'home#portfolio',      :as => :portfolio
  get '/admin'         => 'testimonials#index',  :as => :admin

end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
  validates_presence_of :client_name,:testimonial_content
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  layout 'admin'
  before_filter :authenticate_admin_user!
  before_action :set_testimonial, only: [:show, :edit, :update, :destroy]

  def index
    @testimonials = Testimonial.all
  end

  def show
  end

  def new
    @testimonial = Testimonial.new
  end

  def edit
  end

  def create
    @testimonial = Testimonial.new(testimonial_params)
    if @testimonial.save
      redirect_to @testimonial, notice: 'Testimonial was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @testimonial.update(testimonial_params)
      redirect_to @testimonial, notice: 'Testimonial was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @testimonial.destroy
    redirect_to testimonials_url
  end

  private
    def set_testimonial
      @testimonial = Testimonial.find(params[:id])
    end

    def testimonial_params
      params.require(:testimonial).permit(:client_name,:testimonial_content)
    end
end

app/views/testimonials/_form.html.erb
<%= simple_form_for @testimonial, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :client_name %>
  <%= f.input :testimonial_content %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                testimonials_path, :class => 'btn' %>
  </div>
<% end %>

app/views/testimonials/edit.html.erb
<%- model_class = Testimonial -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/testimonials/index.html.erb
<%- model_class = Testimonial -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:client_name) %></th>
      <th><%= model_class.human_attribute_name(:testimonial_content) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @testimonials.each do |testimonial| %>
      <tr>
        <td><%= link_to testimonial.client_name, testimonial_path(testimonial) %></td>
        <td><%= testimonial.testimonial_content %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_testimonial_path(testimonial), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      testimonial_path(testimonial),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_testimonial_path,
            :class => 'btn btn-primary' %>

app/views/testimonials/new.html.erb
<%- model_class = Testimonial -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/testimonials/show.html.erb
<%- model_class = Testimonial -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:client_name) %>:</strong></dt>
  <dd><%= @testimonial.client_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:testimonial_content) %>:</strong></dt>
  <dd><%= @testimonial.testimonial_content %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              testimonials_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_testimonial_path(@testimonial), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              testimonial_path(@testimonial),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>