config/routes.rb
KeshariyaCompany::Application.routes.draw do
  scope '/admin' do
    resources :careers
    resources :projects
	  resources :project_types
	  resources :pages
	  resources :testimonials
	  resources :contacts
  end

  devise_for :admin_users
  resource :admin_users, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end
  

  root 'home#index'
  get 'about-us'       => 'home#about_us',       :as => :about_us
  match "contact-us"   => "home#contact_us",     :as => :contact_us,  via: [:get, :post]
  get 'services'       => 'home#services',       :as => :services
  get 'blogs'          => 'home#blogs',          :as => :blogs
  get 'careers'        => 'home#careers',        :as => :careers_main
  get 'portfolio-list' => 'home#portfolio_list', :as => :portfolio_list
  get '/portfolio/:id' => 'home#portfolio',      :as => :portfolio
  get '/admin'         => 'testimonials#index',  :as => :admin

end

app/views/layouts/_footer.html.erb
<footer id="footer">
  <div class="container">
    <div class="row">
      <div class="span4">
        <div id="text-2" class="widget widget_text">
          <h3 class="widgettitle title m_title">About Apsolute</h3>
          <div class="textwidget"> ApSolute Technologies a passionate group of developers, designers, thinkers and doers.<br/><br/>Our team is happiest when challenged to turn difficult problems into elegant solutions.<br/><br/>Our mission is to create and launch amazing products.</div>
        </div>
      </div>
      <div class="span4">
        <div id="sbs_nav_menu-2" class="widget widget_sbs_nav_menu">
          <h3 class="widgettitle m_title">Menus</h3>
          <div class="zn_sbs">
            <div class="menu-footer-menu-container">
              <ul id="menu-footer-menu" class="menu">
                <li id="menu-item-768" class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-7 current_page_item menu-item-768 active">
                  <%= link_to "Home", root_path %>
                </li>
                <li id="menu-item-769" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-769">
                  <%= link_to "About Us", about_us_path %>
                </li>
                <li id="menu-item-772" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-772">
                  <%= link_to "Services", services_path %>
                </li>
                <!-- <li id="menu-item-773" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-773">
                  <%#= link_to "Portfolio", portfolio_list_path %>
                </li> -->
                <li id="menu-item-771" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-771">
                  <%= link_to "Careers", careers_main_path %>
                </li>
                <li id="menu-item-770" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-770">
                  <%= link_to "Contact", contact_us_path %>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="span4">
        <div id="text_contact-2" class="widget widget_text_contact">
          <h3 class="widgettitle m_title">GET IN TOUCH</h3>
          <div class="textwidget contact-details">
            <p>
              Address:&nbsp;Ahmedabad, Gujarat, India
            </p>
            <p>
              Email:&nbsp;<a href="#">apsolutetechnology@gmail.com</a>
            </p>
            <p> 
              <strong>Phone:&nbsp;(9179) 40326868</strong>
            </p>
            <p>
            <ul class="social-icons  socnav navRight">
              <li class="social-facebook">
                <a href="https://www.facebook.com/dipak.keshariya.3" target="_blank">Facebook</a>
              </li>
              <li class="social-twitter">
                <a href="https://twitter.com/ApSoluteTech" target="_blank">Twitter</a>
              </li>
              <li class="social-gplus">
                <a href="https://plus.google.com/u/0/113683917761543645898/posts?rel=auther" target="_blank">Google+</a>
              </li>
              <li class="social-linkedin">
                <a href="http://www.linkedin.com/pub/apsolute-technologie-hiring-ror-wordpress-cocos-2dx-developer/88/67/410" target="_blank">Linkedin</a>
              </li>
              <li class="social-skype">
                <a href="skype:dipak.aplosute?userinfo" target="_blank">Skype</a>
              </li>
            </ul>
            </p>
          </div>
        </div>
      </div>
    </div>
    <!-- end row -->
    <div class="row">
      <div class="span12">
        <div class="bottom fixclear">
          <div class="copyright">
            <a href="http://www.apsolutetechnologies.com/"><img src="/assets/logo2.png" alt=""></a>
            <p>&copy; 2014 Copyright by Apsolute Technologies. All rights reserved.</p>
          </div>
          <!-- end copyright -->
        </div>
        <!-- end bottom -->
      </div>
    </div>
    <!-- end row -->
  </div>
</footer>
<script type="text/javascript">

  /* <![CDATA[ */
  var uberMenuSettings = {"speed":"300","trigger":"hoverIntent","orientation":"horizontal","transition":"slide","hoverInterval":"20","hoverTimeout":"400","removeConflicts":"on","autoAlign":"on","noconflict":"off","fullWidthSubs":"on","androidClick":"off","iOScloseButton":"on","loadGoogleMaps":"off","repositionOnLoad":"on"};
  /* ]]> */
</script>

app/views/layouts/_header.html.erb
<header id="header" class="style4 ">
  <div class="container">
    <!-- logo -->
    <h1 id="logo"><a href="<%= root_path %>"><img src="/assets/logo.png" alt="Apsolute Technoloy" title="Apsolute Technology"></a></h1>
    <!-- HEADER ACTION -->
    <ul class="social-icons  topnav navRight">
      <li class="social-facebook">
                <a href="https://www.facebook.com/dipak.keshariya.3" target="_blank">Facebook</a>
              </li>
              <li class="social-twitter">
                <a href="https://twitter.com/ApSoluteTech" target="_blank">Twitter</a>
              </li>
              <li class="social-gplus">
                <a href="https://plus.google.com/u/0/113683917761543645898/posts?rel=auther" target="_blank">Google+</a>
              </li>
              <li class="social-linkedin">
                <a href="http://www.linkedin.com/pub/apsolute-technologie-hiring-ror-wordpress-cocos-2dx-developer/88/67/410" target="_blank">Linkedin</a>
              </li>
              <li class="social-skype">
                <a href="skype:dipak.aplosute?userinfo" target="_blank">Skype</a>
              </li>
    </ul>
    <!-- search -->
    <!-- main menu -->
    <nav id="main_menu" class="">
      <div id="megaMenu" class="megaMenuContainer megaResponsive megaResponsiveToggle wpmega-withjs megaMenuOnHover megaFullWidthSubs megaFullWidth megaMenuHorizontal wpmega-autoAlign wpmega-noconflict megaMinimizeResiduals megaResetStyles megaMenu-withjs">
        <div id="megaMenuToggle" class="megaMenuToggle">
          <span class="megaMenuToggle-icon"></span>
        </div>
        <ul id="megaUber" class="megaMenu">
          <li id="menu-item-718" class="menu-item menu-item-type-post_type menu-item-object-page  page_item page-item-7 ss-nav-menu-item-0 ss-nav-menu-item-depth-0 ss-nav-menu-mega ss-nav-menu-mega-alignCenter <%= 'active current-menu-item current_page_item' if current_page?(root_path) %>">
            <%= link_to  (root_path) do %>
              <span class="wpmega-link-title">Home</span>
            <% end %>
          </li>
          <li id="menu-item-763" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children mega-with-sub ss-nav-menu-item-1 ss-nav-menu-item-depth-0 ss-nav-menu-reg um-flyout-align-center <%= 'active current-menu-item current_page_item' if current_page?(about_us_path) %>">
            <%= link_to (about_us_path) do %>
              <span class="wpmega-link-title">About Us</span>
            <% end %>
          </li>
          <li id="menu-item-753" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children mega-with-sub ss-nav-menu-item-2 ss-nav-menu-item-depth-0 ss-nav-menu-mega ss-nav-menu-mega-fullWidth mega-colgroup mega-colgroup-3 ss-nav-menu-mega-alignLeft <%= 'active current-menu-item current_page_item' if current_page?(services_path) %>">
            <%= link_to (services_path) do %>
              <span class="wpmega-link-title">Services</span>
            <% end %>
          </li>
          <!-- <li id="menu-item-728" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children mega-with-sub ss-nav-menu-item-3 ss-nav-menu-item-depth-0 ss-nav-menu-reg um-flyout-align-center <%#= 'active current-menu-item current_page_item' if current_page?(portfolio_list_path) %>">
            <%#= link_to (portfolio_list_path) do %>
              <span class="wpmega-link-title">Portfolio</span>
            <%# end %>
          </li> -->
          <li id="menu-item-766" class="menu-item menu-item-type-post_type menu-item-object-page ss-nav-menu-item-4 ss-nav-menu-item-depth-0 ss-nav-menu-mega ss-nav-menu-mega-alignCenter <%= 'active current-menu-item current_page_item' if current_page?(careers_main_path) %>">
            <%= link_to (careers_main_path) do %>
              <span class="wpmega-link-title">Career</span>
            <% end %>
          </li>
          <li id="menu-item-766" class="menu-item menu-item-type-post_type menu-item-object-page ss-nav-menu-item-4 ss-nav-menu-item-depth-0 ss-nav-menu-mega ss-nav-menu-mega-alignCenter <%= 'active current-menu-item current_page_item'if current_page?(contact_us_path) %>">
            <%= link_to (contact_us_path) do %>
              <span class="wpmega-link-title">Contact Us</span>
            <% end %>
          </li>
        </ul>
      </div>
    </nav>
    <!-- end main_menu -->
  </div>
</header>

app/views/layouts/_services.html.erb
<div class="row ">
  <div class="span4 box image-boxes imgboxes_style1">
    <a class="hoverBorder" href="<%= services_path %>" target="_self">
      <span class="hoverBorderWrapper">
      <img src="/assets/web.png" alt="" title="Web Development">
      <span class="theHoverBorder"></span>
      </span>
      <h6>Read More+</h6>
    </a>
    <h3 class="m_title">Web Development</h3>
    Are your getting your website updated regularly? If yes, are you spending a hoarded wealth on website maintenance? Does your website maintenance company take too long to take care of your needs? Our website maintenance package enables us to manage your site while you get on with your business! Once your website is launched we undertake a whole range of key activities to accomplish the website maintenance activities.
  </div>
  <!-- end span -->
  <div class="span4 box image-boxes imgboxes_style1">
    <a class="hoverBorder" href="<%= services_path %>" target="_self">
      <span class="hoverBorderWrapper">
      <img src="/assets/Mobile-Apps-Recovered.png" alt="" title="Mobile Development">
      <span class="theHoverBorder"></span>
      </span>
      <h6>Read More+</h6>
    </a>
    <h3 class="m_title">Mobile Development</h3>
    ApSolute Technologies offer complete Android/IPhone /Widnows/BlackBarry Apps Development Solutions and has established expertise in mobile space. The company provides complete Android Apps Development Lifecycle ranging from conceptualization, designing, development, integration, testing, app store deployment and maintenance. Apart from this company also offers value added services such as Android Apps Testing and Android Porting-Migration Services.
  </div>
  <!-- end span -->
  <div class="span4 box image-boxes imgboxes_style1">
    <a class="hoverBorder" href="<%= services_path %>" target="_self">
      <span class="hoverBorderWrapper">
      <img src="/assets/seo-icon.png" alt="" title="Dedicated Services">
      <span class="theHoverBorder">
      </span>
      </span>
      <h6>Read More+</h6>
    </a>
    <h3 class="m_title">SEO &amp; Designing </h3>
    Have you been in search for the best web design company to get your corporate website designed? Do you want your website to stand out from the rest of the competition? Do you want to launch a website that performs well online? We have the best answers for all your requirements. We offer the most comprehensive range of web design services. We offer top-notch web design services that will help you impress your customers.
  </div>
  <!-- end span -->
</div>

app/views/layouts/_slider.html.erb
<div id="slideshow" class="uh_zn_def_header_style portfolio_devices zn_slideshow">
  <div class="bgback"></div>
  <div id="rev_slider_1_1_wrapper" class="rev_slider_wrapper fullwidthbanner-container" style="margin:0px auto;background-color:#E9E9E9;padding:5px;margin-top:0px;margin-bottom:0px;max-height:630px;">
    <div id="rev_slider_1_1" class="rev_slider fullwidthabanner revslider-initialised tp-simpleresponsive">
      <ul>
        <!--rs-slider1-->
        <li data-transition="boxfade" data-slotamount="7"  data-masterspeed="300"  title="" data-thumb="../assets/images/thumbs/regular_thumb2.jpg">
          <img src="/assets/banner1.jpg"  >
          <div class="caption para1 fade" data-x="225" data-y="407" data-speed="300" data-start="800" data-easing="easeOutExpo"><img style="width: 495px; height: 149px;" src="/assets/banner1-pc.png" alt="banner-pc-1"></div>
          <div class="caption sft big_bnnr1_black"  data-x="180" data-y="123" data-speed="300" data-start="1100" data-easing="easeOutExpo">Responsive Web Development</div>
          <div class="caption sft small1_bnnr1_black"  data-x="240" data-y="178" data-speed="300" data-start="1400" data-easing="easeOutExpo">
            <p>Does Your Website Make a Splash</p>
          </div>
          <div class="caption para1 lfl" data-x="-12" data-y="460" data-speed="300" data-start="1700" data-easing="easeOutExpo"><img style="width: 71px; height: 72px;" src="/assets/banner1-js.png" alt="Java Script"></div>
          <div class="caption sfr smlcaption_white" data-x="62" data-y="475" data-speed="300" data-start="2000" data-easing="easeOutExpo">
            <p>Javascript</p>
          </div>
          <div class="caption para1 lfl" data-x="162" data-y="336" data-speed="300" data-start="2300" data-easing="easeOutExpo"><img style="width: 65px; height: 72px;" src="/assets/banner1-h5.png" alt="HTML 5"></div>
          <div class="caption sfr smlcaption_white" data-x="234" data-y="352" data-speed="300" data-start="2600" data-easing="easeOutExpo">
            <p>HTML5</p>
          </div>
          <div class="caption sft" data-x="343" data-y="247" data-speed="300" data-start="2900" data-easing="easeOutExpo"><img style="width: 325px; height: 82px; " src="/assets/banner1-gif.gif" alt="gif" /></div>
          <div class="caption para1 sfr" data-x="645" data-y="336" data-speed="300" data-start="3200" data-easing="easeOutExpo"><img style="width: 66px; height: 74px;" src="/assets/banner1-c3.png" alt="CSS 3"></div>
          <div class="caption sfr smlcaption_white" data-x="720" data-y="352" data-speed="300" data-start="3500" data-easing="easeOutExpo">
            <p>CSS3</p>
          </div>
          <div class="caption para1 lfr" data-x="747" data-y="460" data-speed="300" data-start="3800" data-easing="easeOutExpo"><img style="width: 77px; height: 73px;" src="/assets/banner1-jquery.png" alt="Java Script"></div>
          <div class="caption sfr smlcaption_white" data-x="836" data-y="475" data-speed="300" data-start="4100" data-easing="easeOutExpo">
            <p>Jquery</p>
          </div>
          <div class="caption sfb" data-x="835" data-y="537" data-speed="1000"
            data-start="2600" data-easing="easeOutBack"><a href="<%= contact_us_path %>"
            target="_self" class="tp-button blue small">Get a Quote</a></div>
        </li>
        <li data-transition="random" data-slotamount="7"  data-masterspeed="300"  title="" data-thumb="../assets/images/thumbs/regular_thumb3.jpg">
          <img src="/assets/banner3.jpg"  >
          <div class="caption para3 fade" data-x="14" data-y="236" data-speed="300" data-start="1200" data-easing="easeOutExpo"><img style="width: 500px; height: 215px;" src="/assets/banner3-disgn.png" alt="banner2-sco"></div>
          <div class="caption para3 lft" data-x="166" data-y="95" data-speed="300" data-start="1800" data-easing="easeOutExpo"><img style="width: 197px; height: 199px;" src="/assets/banner3-devlp.png" alt="banner3-devlp"></div>
          <div class="caption para3 lfb" data-x="163" data-y="394" data-speed="300" data-start="2000" data-easing="easeOutExpo"><img style="width: 202px; height: 197px;" src="/assets/banner3-mob.png" alt="banner3-mob"></div>
          <div class="caption sfr big_white"  data-x="525" data-y="180" data-speed="300" data-start="2400" data-easing="easeOutExpo">Web &amp; Mobile Application<br/>Development</div>
          <div class="caption lfb small_white_bannr"  data-x="528" data-y="295" data-speed="300" data-start="2800" data-easing="easeOutExpo">
            <p>Our website maintenance package<br/>enables us to manage your site while<br/>you get on with your business!</p>
          </div>
          <div class="caption lfb small_white_bannr"  data-x="528" data-y="396" data-speed="300" data-start="3200" data-easing="easeOutExpo">
            <p>We offer complete Android /IPhone /Widnows<br/>/BlackBarry Apps Development Solutions<br/>and has established expertise<br/>in mobile space.</p>
          </div>
          <div class="caption sfb" data-x="835" data-y="537" data-speed="1000"
            data-start="2600" data-easing="easeOutBack"><a href="<%= contact_us_path %>"
            target="_self" class="tp-button blue small">Get a Quote</a></div>
        </li>
        <li data-transition="random" data-slotamount="7"  data-masterspeed="300"  title="" data-thumb="../assets/images/thumbs/regular_thumb2.jpg">
          <img src="/assets/banner2.jpg"  >
          <div class="caption para3 sft" data-x="14" data-y="135" data-speed="300" data-start="1700" data-easing="easeOutExpo"><img style="width: 393px; height: 451px;" src="/assets/banner2-sco.png" alt="banner2-sco"></div>
          <div class="caption sfr big_black"  data-x="521" data-y="240"
            data-speed="300" data-start="2600" data-easing="easeOutExpo">SEO
            Service
          </div>
          <div class="caption lfb
            small_cap_bnnr2"  data-x="526" data-y="340" data-speed="300"
            data-start="2900" data-easing="easeOutExpo">
            <p>With our customized SEO
              services<br/>we make your website visible<br/>to your potential
              customers.
            </p>
          </div>
          <div class="caption sfb" data-x="835" data-y="537" data-speed="1000"
            data-start="2600" data-easing="easeOutBack"><a href="<%= contact_us_path %>"
            target="_self" class="tp-button blue small">Get a Quote</a></div>
        </li>
        <li data-transition="boxfade" data-slotamount="7"  data-masterspeed="300"  title="" data-thumb="../assets/images/thumbs/regular_thumb4.jpg">
          <img src="/assets/banner4.jpg"  >
          <div class="caption para1 fade" data-x="364" data-y="279" data-speed="300" data-start="800" data-easing="easeOutExpo"><img src="/assets/logo_on_slider.png" alt="apsolute-logo"></div>
          <div class="caption para1 fade"  data-x="229" data-y="148" data-speed="300" data-start="1100" data-easing="easeOutExpo"><img style="width:481px; height:319px;" src="/assets/banner4-ring1.png" alt="ring1"></div>
          <div class="caption para1 fade"  data-x="211" data-y="136" data-speed="400" data-start="1400" data-easing="easeOutExpo"><img style="width:517px; height:343px;" src="/assets/banner4-ring2.png" alt="ring2"></div>
          <div class="caption para1 sft" data-x="410" data-y="105" data-speed="400" data-start="1700" data-easing="easeOutExpo"><img src="/assets/banner4-analysis.png" alt="Analysis"></div>
          <div class="caption para1 lfr" data-x="633" data-y="190" data-speed="400" data-start="2000" data-easing="easeOutExpo"><img src="/assets/banner4-dsgn.png" alt="Design"></div>
          <div class="caption para1 sfr" data-x="601" data-y="356" data-speed="400" data-start="2300" data-easing="easeOutExpo"><img src="/assets/banner4-code.png" alt="Codding"></div>
          <div class="caption para1 sfb" data-x="410" data-y="414" data-speed="400" data-start="2600" data-easing="easeOutExpo"><img src="/assets/banner4-testng.png" alt="Testing"></div>
          <div class="caption para1 sfl" data-x="216" data-y="356" data-speed="400" data-start="2900" data-easing="easeOutExpo"><img src="/assets/banner4-maintnce.png" alt="Maintenance"></div>
          <div class="caption para1 lfl" data-x="171" data-y="190" data-speed="400" data-start="3000" data-easing="easeOutExpo"><img src="/assets/banner4-prjct.png" alt="Project Plannig"></div>
          <div class="caption para1 fade" data-x="552" data-y="143" data-speed="400" data-start="3300" data-easing="easeOutExpo"><img src="/assets/banner4-analysis-arrow.png" alt="Arrow"></div>
          <div class="caption para1 fade" data-x="697" data-y="287" data-speed="400" data-start="3600" data-easing="easeOutExpo"><img src="/assets/banner4-dsgn-arrow.png" alt="Arrow"></div>
          <div class="caption para1 fade" data-x="577" data-y="432" data-speed="400" data-start="3900" data-easing="easeOutExpo"><img src="/assets/banner4-code-arrow.png" alt="Arrow"></div>
          <div class="caption para1 fade" data-x="362" data-y="448" data-speed="400" data-start="4000" data-easing="easeOutExpo"><img src="/assets/banner4-testng-arrow.png" alt="Arrow"></div>
          <div class="caption para1 fade" data-x="203" data-y="337" data-speed="400" data-start="4300" data-easing="easeOutExpo"><img src="/assets/banner4-maintnce-arrow.png" alt="Arrow"></div>
          <div class="caption para1 fade" data-x="279" data-y="170" data-speed="400" data-start="4600" data-easing="easeOutExpo"><img src="/assets/banner4-prjct-arrow.png" alt="Arrow"></div>
          <div class="caption sfb" data-x="835" data-y="537" data-speed="1000" data-start="2600" data-easing="easeOutBack"><a href="<%= contact_us_path %>" target="_self" class="tp-button blue small">Get a Quote</a></div>
        </li>
      </ul>
      <div class="tp-bannertimer"></div>
      <div style="display: none;" class="tp-loader"></div>
    </div>
    <!-- /rev_banner -->
    <div class="tp-bannershadow tp-shadow2"></div>
    <div class="tp-leftarrow tparrows default hidearrows"></div>
    <div class="tp-rightarrow tparrows default hidearrows"></div>
  </div>
  <div class="dc_clear"></div>
  <!-- line break/clear line -->
  <!-- DC Revolution Slider Settings -->
  <script type="text/javascript">
    var tpj=jQuery;
    tpj.noConflict();
    
    tpj(document).ready(function() {
    
    if (tpj.fn.cssOriginal!=undefined)
        tpj.fn.css = tpj.fn.cssOriginal;
    
        tpj('#rev_slider_1_1').revolution(
            {
                delay:9000,
    startwidth:960,
    startheight:630,
    hideThumbs:200,
    
    thumbWidth:100,
    thumbHeight:50,
    thumbAmount:3,
    
    navigationType:"none",
    navigationArrows:"solo",
    navigationStyle:"square-old",
    
    touchenabled:"on",
    onHoverStop:"on",
    
    navigationHAlign:"right",
    navigationVAlign:"bottom",
    navigationHOffset:0,
    navigationVOffset:20,
    
    soloArrowLeftHalign:"left",
    soloArrowLeftValign:"center",
    soloArrowLeftHOffset:20,
    soloArrowLeftVOffset:0,
    
    soloArrowRightHalign:"right",
    soloArrowRightValign:"center",
    soloArrowRightHOffset:20,
    soloArrowRightVOffset:0,
    
    shadow:2,
    fullWidth:"on",
    
    stopLoop:"off",
    stopAfterLoops:-1,
    stopAtSlide:-1,
    
    shuffle:"off",
    
    hideSliderAtLimit:0,
    hideCaptionAtLimit:0,
    hideAllCaptionAtLilmit:0,
    startWithSlide:0                          // on == Stop loop at the last Slie,  off== Loop all the time.
            });
    
        });
    
  </script> 
  <!-- END REVOLUTION SLIDER -->
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= full_title_for_backend(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "admin", :media => "all" %>
    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "admin" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<%= admin_path %>">Apsolute Technologies</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Careers", careers_path  %></li>
              <li><%= link_to "Contacts", contacts_path  %></li>
              <li><%= link_to "Pages", pages_path  %></li>
              <!-- <li><%#= link_to "Projects", projects_path  %></li>
              <li><%#= link_to "Project Type", project_types_path  %></li> -->
              <li><%= link_to "Testimonials", testimonials_path  %></li>
              <li><%= link_to "Change Password", edit_admin_users_path  %></li>
              <li><%= link_to "Logout", destroy_admin_user_session_path, method: :delete  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
    </div> <!-- /container -->
  </body>
</html>